blank_issues_enabled: false
contact_links:
  - name: Product Questions
    url: https://github.com/MilleBii/visite-plus/discussions
    about: Use discussions for open product questions and brainstorming.
